IDEA-224584: Fix filter
JetBrains/intellij-community pull request #1467
Opened 2020-11-02 13:48 UTC by heckad

https://youtrack.jetbrains.com/issue/IDEA-224584

2020-11-02 19:33 UTC, ybedrov commented
Hello!

Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

2020-11-02 22:40 UTC, heckad commented
@ybedrov, yes I have.

2020-11-03 10:23 UTC, yole requested changes

2020-11-03 10:23 UTC, yole commented on platform/lang-impl/src/com/intellij/ide/util/PsiElementListCellRenderer.java
> -    installSpeedSearch(builder, false);
Please don't change the default behavior of this method. If you need `includeContainerText` to be true in a specific place, please make a change to that place.

2020-11-13 10:40 UTC, yole commented
Merged manually, thanks!

2020-11-13 10:40 UTC, closed without merging