Task/update inspection gadget descriptions
JetBrains/intellij-community pull request #1535
Opened 2021-04-04 19:12 UTC by ascopes

- Fixes several occurrences where `<` and `>` may be interpreted as HTML tags rather than literal symbols,
  which has manifested itself as a visual error in at least one place:

![image](https://user-images.githubusercontent.com/73482956/113519040-ce561580-9581-11eb-8893-9bdc5fef6748.png)

- Moved comments in SerializableRecordContainsIgnoredMembers.html to aid in readability and reduce content that
  scrolls horizontally or wraps in the preview/tooltip.

- Added additional comments to PointlessBitwiseExpression.html, as some semantics of how Java deals with bitwise operations
  and integral limits may be considered to be outside the range of beginner knowledge, and thus a common "gotcha" to developers.

2021-04-05 09:57 UTC, BasLeijdekkers commented
Hello!
Have you signed a contributor license agreement? If you haven't yet, you can do that here:
https://www.jetbrains.com/agreements/cla
Thanks.

2021-04-05 11:28 UTC, ascopes commented
@BasLeijdekkers all signed and completed. Thanks for providing the link.

Also checked the failing code inspection check; [it appears that it has passed, but that the GitHub integration is not picking it up](https://web.sssa.aws.intellij.net/index.html?id=GHPRaa8f72ae0f7ac3385ccf90fbafc187d5b157ec5f9cf9d5d26575b5be0f90f8d8&url=https%3A%2F%2Fweb.sssa.aws.intellij.net%2Fresults&locationFilters=NoXSA&genericFilters=N4XyA&orderedLevels=NoIgLg9hA2IDQgM4FMBuyBOBLMBPeIAxgIZjIDmEG%2BCeADsiALpA), so hopefully it should be good to go now.

2021-04-05 14:54 UTC, BasLeijdekkers requested changes
Could you squash your commits into one? That will make it easier to merge (we don't use GitHub for this, but merge manually into our repository which get synced with GitHub after that).

2021-04-05 14:54 UTC, BasLeijdekkers commented on plugins/InspectionGadgets/src/inspectionDescriptions/AssertWithSideEffects.html
> -  assert i++ < 10;
Could you keep the 2 space indent? It is nicer in the UI when the code examples are indented a litte.

2021-04-05 18:12 UTC, ascopes commented
> Could you keep the 2 space indent? 
Done.

> Could you squash your commits into one?

And done :+1:

2021-04-06 11:43 UTC, BasLeijdekkers approved these changes

2021-04-06 13:30 UTC, BasLeijdekkers commented
Merged manually as 91df514dad521c7073bd0e6fa54e43806d93ab36
It may take a while before this is visible in the GitHub repo.
Thank you for your contribution!

2021-04-06 13:30 UTC, closed without merging