[IDEA-37227] Add new "Boolean expression may be factorized" inspection
JetBrains/intellij-community pull request #1576
Opened 2021-06-09 17:04 UTC by Fabrice-TIERCELIN

[Creates a new inspection that factorizes boolean expression when possible](https://youtrack.jetbrains.com/issue/IDEA-37227):

`isValid && isFound || isValid && isActive`

becomes:

`isValid && (isFound || isActive)`

2021-06-09 17:08 UTC, Fabrice-TIERCELIN commented
@BasLeijdekkers,

I have managed to squash the Pull Request of the #1550 but I deleted and recreated my repository to do so. The unexpected result is that the diff is not updated so I recreate the PR.

2021-06-09 17:32 UTC, Fabrice-TIERCELIN commented
@BasLeijdekkers,

Yes, it can be applied to numeric too. I wanted to code a simple dev first and extend it later.
But you may think we should not rebrand this inspection in the future...
Do you prefer me to code this inspection for numeric now?

2021-06-11 09:35 UTC, BasLeijdekkers commented
It would be nice to be able to factorize numeric expressions as well at some point, but I think it is not necessary for this pull request. However it seems to me the following boolean can also be factorized:
```
boolean w = (a || b) && (a || c);
```
to:
```
boolean w = a || b && c;
```
Do you think the inspection can be modified to handle this as well?

2021-06-11 09:36 UTC, BasLeijdekkers requested changes

2021-06-11 09:36 UTC, BasLeijdekkers commented on plugins/InspectionGadgets/InspectionGadgetsAnalysis/resources/messages/InspectionGadgetsBundle.properties
> +boolean.expression.may.be.factorized.display.name=Boolean expression could have a factorized expression
I think an inspection name like "Boolean expression can be factorized" would be shorter and clearer.

2021-06-11 09:36 UTC, BasLeijdekkers commented on plugins/InspectionGadgets/InspectionGadgetsAnalysis/resources/messages/InspectionGadgetsBundle.properties
> +if.may.be.factorized.problem.descriptor=<code>#ref</code> could have a factorized expression #loc
For the problem descriptor as well: "x an be factorized"

2021-06-11 09:36 UTC, BasLeijdekkers commented on plugins/InspectionGadgets/InspectionGadgetsAnalysis/src/com/siyeh/ig/controlflow/BooleanExpressionMayBeFactorizedInspection.java
> +      if (EquivalenceChecker.getCanonicalPsiEquivalence().expressionsAreEquivalent(expression1, expression2) && !SideEffectChecker.mayHaveSideEffects(expression1)) {
NPE on `() && b || () && c`.

2021-06-11 09:36 UTC, BasLeijdekkers commented on plugins/InspectionGadgets/src/META-INF/InspectionGadgets.xml
> +                     groupKey="group.names.control.flow.issues" enabledByDefault="false" level="WARNING"
Please enable by default with `level="INFORMATION"`.

2021-06-11 09:36 UTC, BasLeijdekkers commented on plugins/InspectionGadgets/src/inspectionDescriptions/BooleanExpressionMayBeFactorized.html
> +<pre>a &amp;&amp; b || a &amp;&amp; c;</pre>
For the 2021.2 release we have standardized the format of the example part of the description. It looks like this:
```
<p><b>Example:</b></p>
<pre><code>
  <!-- example here -->
</code></pre>
<p>After the quick-fix is applied:</p>
<pre><code>
  <!-- fixed example here -->
</code></pre>
```
Also you could remove the semicolons. They are not relevant for the example and the statement is not compilable anyway.

2021-06-11 16:43 UTC, closed without merging