PY-48747 allow all valid Python identifers in target name; fix message
JetBrains/intellij-community pull request #1607
Opened 2021-06-27 17:26 UTC by nobodxbodon

Target with a name containing non-ASCII characters now runs without error prompts.

2021-06-28 21:50 UTC, throwable-one requested changes

2021-06-29 00:11 UTC, nobodxbodon commented on python/src/com/jetbrains/extensions/TargetWithVariantExt.kt
> +  PyRunTargetVariant.PYTHON -> PyNames.isIdentifier((target ?: "").replace(".", "_"))
@throwable-one Thanks for the quick response. 

I just tested with case below:
```python
    def test2..(self):
        pass
```
The auto-generated target name will be "Test.Test.test2":
<img width="643" alt="Screen Shot 2021-06-28 at 4 58 04 PM" src="https://user-images.githubusercontent.com/392497/123717696-368b5f00-d832-11eb-83af-d1d23fa78c2f.png">

I guess somewhere in the code trimmed the invalid dot part. Is it OK to ignore this case in validation then?

Yes I've signed contributor agreement.

2021-06-29 18:20 UTC, throwable-one commented on python/src/com/jetbrains/extensions/TargetWithVariantExt.kt
> +  PyRunTargetVariant.PYTHON -> PyNames.isIdentifier((target ?: "").replace(".", "_"))
But when user creates configuration manually she can do something like
![image](https://user-images.githubusercontent.com/7673963/123847772-a4618480-d91f-11eb-9ef4-7e383f65f4ff.png)

It is valid to have several underscores in Java, but not several dots in Python, this is why we suggested

```
PyRunTargetVariant.PYTHON -> target?.let { it.split(".").all { PyNames.isIdentifier(it) } } ?: true
```

2021-06-29 21:32 UTC, nobodxbodon commented on python/src/com/jetbrains/extensions/TargetWithVariantExt.kt
> +  PyRunTargetVariant.PYTHON -> PyNames.isIdentifier((target ?: "").replace(".", "_"))
Thanks for explaining. I thought user can freely change target name without impacting the test behavior, but after some more tests I now realize it's not true.

I agree it's better to have stricter syntax checking here. I just made another commit as you suggested.

2021-07-02 06:01 UTC, closed without merging