Add managed plugin truststore
JetBrains/intellij-community pull request #1629
Opened 2021-07-14 06:34 UTC by brian-mcnamara

2021-07-14 06:35 UTC, brian-mcnamara commented
I could use some help tracking down a test class I could add a test to. Any ideas?

2021-07-15 07:56 UTC, AlexanderPrendota requested changes

2021-07-15 07:56 UTC, AlexanderPrendota commented on platform/platform-impl/src/com/intellij/ide/plugins/certificates/PluginCertificateStore.kt
> +    val keystoreFile = File(storePath)
I would suggest using `Path` instead of File

2021-07-15 12:38 UTC, AlexanderPrendota requested changes

2021-07-15 12:38 UTC, AlexanderPrendota commented on platform/platform-impl/src/com/intellij/ide/plugins/certificates/PluginCertificateStore.kt
> +        for (alias in keystore.aliases()) {
```kotlin
keystore.aliases().mapNotNull{ keystore.getCertificate(alias) as? X509Certificate) }
```

2021-07-20 17:16 UTC, brian-mcnamara commented
Its merged in to 212 branch and main https://github.com/JetBrains/intellij-community/commit/a9397aa0ce5c3964cbf5b50294b12d4447b4f01f

2021-07-20 17:16 UTC, closed without merging

2021-07-20 17:27 UTC, AlexanderPrendota commented
thanks =)