[EE-IR] Local Function Support
JetBrains/intellij-community pull request #1973
Opened 2022-03-28 09:01 UTC by kandersen

This commit introduces support for calls and references to functions and objects
local to the breakpoint. This commit is supported by corresponding changes in
the compiler.

The commit includes:
  - refined test coverage
  - separation of code-paths for old and new evaluator backends.
  - justification for every remaining muted test included in the suite

Known outstanding issues:
  - referencing local classes from the fragment
  - declarations in the fragment itself
  - result of when-expressions in the fragment is discarded
  - access to protected top level members in `root` package
  - (a handful of tests fail due to disparities in stepping and breaking
    behavior between the JVM and the IR backends)

2022-03-28 09:05 UTC, kandersen commented
@nikita-nazarov The plug-in side changes are ready for review. Compiler side changes are on their way.

The separation of JVM and IR backend is a little ad-hoc in CodeFragmentCompiler: there's just an interface with a method for every point of variability. Perhaps two separate, although similar, versions of CodeFragmentCompiler would have been cleaner -- it will be easier to throw away the JVM implementation later, as that would just be a few lines changed in KotlinEvaluatorBuilder, whereas currently it should probably include massaging CodeFragmentCompiler to get rid of the indirection via the interface. It's a trade-off, where in the current situation we avoid a lot of code duplication.

2022-03-29 09:20 UTC, nikita-nazarov requested changes
Thanks for your work! I will merge the pr after compiler changes are merged.

2022-03-29 09:20 UTC, nikita-nazarov commented on plugins/kotlin/jvm-debugger/test/testData/evaluation/singleBreakpoint/simpleLocals/localFunctionWithArg.kt
> +Test what button do I actually use for space? It seems to be the right thumb exsclusively! :D I never noticed but I guess it can be untaught
I use the left one! 😄

2022-03-29 10:43 UTC, kandersen commented on plugins/kotlin/jvm-debugger/evaluation/src/org/jetbrains/kotlin/idea/debugger/evaluate/FragmentProjectFileDependencyCollector.kt
> +                val thisReceiver = (descriptor.dispatchReceiverParameter as ReceiverParameterDescriptor).value as? ThisClassReceiver ?: return
Done!

2022-03-29 10:46 UTC, kandersen commented on plugins/kotlin/jvm-debugger/evaluation/src/org/jetbrains/kotlin/idea/debugger/evaluate/KotlinEvaluatorBuilder.kt
> +                if (!CodeFragmentCompiler.useIRFragmentCompiler(debugProcess)) {
Thanks! Done.

2022-03-29 10:47 UTC, kandersen commented on plugins/kotlin/jvm-debugger/evaluation/src/org/jetbrains/kotlin/idea/debugger/evaluate/compilation/IRFragmentCompilerCodegen.kt
> +                // for top level declarations (as the facade classes do not exist in the PSI but areV
Good catch!

2022-03-29 10:47 UTC, kandersen commented on plugins/kotlin/jvm-debugger/evaluation/src/org/jetbrains/kotlin/idea/debugger/evaluate/compilation/IRFragmentCompilerCodegen.kt
> +        val processedOldCaptures: List<CodeFragmentParameter.Smart> = parameterInfo.parameters.map { it ->
Done!.

2022-03-29 10:49 UTC, kandersen commented on plugins/kotlin/jvm-debugger/evaluation/src/org/jetbrains/kotlin/idea/debugger/evaluate/compilation/IRFragmentCompilerCodegen.kt
> +        CodeFragmentParameterAnalyzer(executionContext, codeFragment, bindingContext, status).analyze().let {
Done!

2022-03-29 10:50 UTC, kandersen commented on plugins/kotlin/jvm-debugger/evaluation/src/org/jetbrains/kotlin/idea/debugger/evaluate/compilation/CodeFragmentCompiler.kt
> +            fragmentCompilerBackend.configureGenerationState(this, bindingContext, compilerConfiguration, classDescriptor, methodDescriptor, parameterInfo)
Split!

2022-03-29 10:51 UTC, kandersen commented on plugins/kotlin/jvm-debugger/evaluation/src/org/jetbrains/kotlin/idea/debugger/evaluate/compilation/CodeFragmentCompiler.kt
> +    fun initBackend(codeFragment: KtCodeFragment): FragmentCompilerCodegen {
Done

2022-03-29 11:06 UTC, kandersen commented
Thank you for the review! I have push all, and will keep you in the loop on the compiler side changes :+1:

2022-04-25 14:23 UTC, nikita-nazarov commented
https://github.com/JetBrains/intellij-community/commit/0d9b42206001b3ebdecec9d802f5adedfa0b6fec
https://github.com/JetBrains/intellij-community/commit/81e683cd5b6dbf4ba4f2affda75f1a1e90a9c93b

2022-04-25 14:23 UTC, closed without merging