KTIJ-24134 False positive 'Remove unnecessary parentheses from function call with lambda' inspection is displayed together with 'no value for parameter' error
JetBrains/intellij-community pull request #2505
Opened 2023-07-02 00:14 UTC by t-kameyama

https://youtrack.jetbrains.com/issue/KTIJ-24134

2023-07-03 10:20 UTC, abelkov commented
@darthorimar can you please check is it OK from K2 API point of view?

2023-07-03 13:40 UTC, darthorimar requested changes

2023-07-03 13:40 UTC, darthorimar commented on plugins/kotlin/code-insight/inspections-shared/src/org/jetbrains/kotlin/idea/codeInsight/inspections/shared/RemoveEmptyParenthesesFromLambdaCallInspection.kt
> -class RemoveEmptyParenthesesFromLambdaCallInspection : AbstractKotlinApplicableInspection<KtValueArgumentList>(KtValueArgumentList::class),
You can simply override `AbstractKotlinApplicableInspection .isApplicableByAnalyze` instead of rewriting the inspection to `AbstractKotlinInspection`

2023-07-03 14:13 UTC, t-kameyama commented on plugins/kotlin/code-insight/inspections-shared/src/org/jetbrains/kotlin/idea/codeInsight/inspections/shared/RemoveEmptyParenthesesFromLambdaCallInspection.kt
> -class RemoveEmptyParenthesesFromLambdaCallInspection : AbstractKotlinApplicableInspection<KtValueArgumentList>(KtValueArgumentList::class),
Cannot be overridden

<img width="1193" alt="スクリーンショット 2023-07-03 23 12 53" src="https://github.com/JetBrains/intellij-community/assets/1121855/8a5927ec-1e2c-4e27-b2e1-bef60e626a6f">
<img width="1011" alt="スクリーンショット 2023-07-03 23 13 06" src="https://github.com/JetBrains/intellij-community/assets/1121855/a9a0d6d2-4abc-4f07-98ba-351ba8d93c4a">

2023-07-05 06:33 UTC, darthorimar commented on plugins/kotlin/code-insight/inspections-shared/src/org/jetbrains/kotlin/idea/codeInsight/inspections/shared/RemoveEmptyParenthesesFromLambdaCallInspection.kt
> -class RemoveEmptyParenthesesFromLambdaCallInspection : AbstractKotlinApplicableInspection<KtValueArgumentList>(KtValueArgumentList::class),
I've enabled the context receiver support in the shared module (https://github.com/JetBrains/intellij-community/commit/9661fc272d9d4deeac8f19eb2d23672b683252a2) now it should work

2023-07-05 07:20 UTC, t-kameyama commented on plugins/kotlin/code-insight/inspections-shared/src/org/jetbrains/kotlin/idea/codeInsight/inspections/shared/RemoveEmptyParenthesesFromLambdaCallInspection.kt
> -class RemoveEmptyParenthesesFromLambdaCallInspection : AbstractKotlinApplicableInspection<KtValueArgumentList>(KtValueArgumentList::class),
Fixed. [fba57e8](https://github.com/JetBrains/intellij-community/pull/2505/commits/fba57e831b574699254ae75c7b5f448e57814a14)

2023-07-05 11:23 UTC, darthorimar commented
@t-kameyama please squash commits into one and get rid of a merge commit, otherwise LGTM 👍

2023-07-05 14:51 UTC, t-kameyama commented
> @t-kameyama please squash commits into one and get rid of a merge commit, otherwise LGTM 👍

Done

2023-07-05 16:16 UTC, darthorimar approved these changes

2023-07-12 10:40 UTC, abelkov approved these changes

2023-07-12 18:58 UTC, closed without merging