[KTIJ-4113] - Enabling align when multiline option for chained methods
JetBrains/intellij-community pull request #2524
Opened 2023-07-27 05:04 UTC by DanielFidalgo

This PR makes the option 'Align when multiline' available for chained method calls that are wrapped.
Continuation indent still takes precedence and the option being anabled will only work when continuation indent is disabled.

2023-07-27 08:43 UTC, dimonchik0036 requested changes
Please add tests for many different cases. Such changes should be well covered.
Also, the commit message is not properly formatted. Should be something like this:
```
[kotlin][formatter] Enable align when multiline option for chained methods

^KTIJ-4113 Fixed
```
[CONTRIBUTING.md](https://github.com/JetBrains/intellij-community/blob/master/plugins/kotlin/CONTRIBUTING.md#3-pull-request-requirements)

2023-08-01 21:15 UTC, DanielFidalgo commented
> Please add tests for many different cases. Such changes should be well covered. Also, the commit message is not properly formatted. Should be something like this:
> 
> ```
> [kotlin][formatter] Enable align when multiline option for chained methods
> 
> ^KTIJ-4113 Fixed
> ```
> 
> [CONTRIBUTING.md](https://github.com/JetBrains/intellij-community/blob/master/plugins/kotlin/CONTRIBUTING.md#3-pull-request-requirements)

Added test file and fixed commit message

2023-08-10 09:57 UTC, dimonchik0036 requested changes
In Kotlin, we also have safe call chains (`a?.b`). Could you please add tests for this case too?
They can be mixed with regular dot calls in any order

2023-08-12 23:11 UTC, DanielFidalgo commented
> In Kotlin, we also have safe call chains (`a?.b`). Could you please add tests for this case too? They can be mixed with regular dot calls in any order

Added test file for safe access chain call testing

2023-08-12 23:11 UTC, closed without merging

2023-08-12 23:13 UTC, DanielFidalgo commented
And I closed the PR thinking I was closing the change request 🤦

2023-08-12 23:28 UTC, DanielFidalgo commented
Opened new pull request on https://github.com/JetBrains/intellij-community/pull/2540 in case this PR cannot be reopened