KTIJ-26406 False negative "Unused unary operator" with more than one operator on same line
JetBrains/intellij-community pull request #2525
Opened 2023-07-27 05:36 UTC by t-kameyama

https://youtrack.jetbrains.com/issue/KTIJ-26406

<img width="560" alt="スクリーンショット 2023-07-27 14 35 10" src="https://github.com/JetBrains/intellij-community/assets/1121855/58f6d834-b4fa-411f-8dbf-bdffe7b293e5">

2023-07-27 07:55 UTC, abelkov commented on plugins/kotlin/idea/src/org/jetbrains/kotlin/idea/inspections/UnusedUnaryOperatorInspection.kt
> -        if (prefix.isInAnnotationEntry) return
This line is still needed, even though tests pass without it :( I will expand the comment.

2023-07-27 08:37 UTC, abelkov requested changes
Sorry, after your change there is a lot of new warnings on intellij-community project, please fix the inspection before we can commit this.

2023-07-27 14:58 UTC, abelkov commented
Can you please add a test for the false positive case that was found in intellij-community?

2023-07-28 00:47 UTC, t-kameyama commented
Added

2023-07-28 07:45 UTC, abelkov approved these changes

2023-07-28 09:55 UTC, closed without merging

2023-07-28 15:28 UTC, vladimirdolzhenko commented
Thanks a lot for the contribution