Remove "Open" From REDUNDANT_OPEN_IN_INTERFACE during JKTree
JetBrains/intellij-community pull request #2641
Opened 2024-01-22 16:10 UTC by jocelynluizzi13

move the REDUNDANT_OPEN_IN_INTERFACE check so that it looks for methods inside of interfaces during JKCodebuilder and removes it there

2024-01-23 09:51 UTC, abelkov requested changes

2024-01-23 09:51 UTC, abelkov commented on .idea/vcs.xml
This PR should consist of a single commit and should not contain changes to `.idea` directory. You can force push your branch after removing redundant commits.

I have created a tracking issue for this work: https://youtrack.jetbrains.com/issue/KTIJ-28575/K2-J2K-Convert-Post-processings-to-JKTree-conversions

Please write the commit message in the following format:

```
[kotlin] J2K: Convert REDUNDANT_OPEN_IN_INTERFACE post-processing to a JK conversion

KTIJ-28575
```

2024-01-23 09:51 UTC, abelkov commented on plugins/kotlin/j2k/k1.new/src/org/jetbrains/kotlin/nj2k/printing/JKCodeBuilder.kt
> +        return printer.toString().replace("\r\n", "\n")
This is unreachable code, should be removed.

2024-01-23 09:51 UTC, abelkov commented on plugins/kotlin/j2k/k1.new/src/org/jetbrains/kotlin/nj2k/printing/JKCodeBuilder.kt
> +                ktConvertedFromForLoopSyntheticWhileStatement.variableDeclarations, ::ensureLineBreak
This is a pure formatting change, please put such changes into a separate commit. Also, the correct formatting here is:

```
 printer.renderList(ktConvertedFromForLoopSyntheticWhileStatement.variableDeclarations, ::ensureLineBreak) {
    it.accept(this)
}
```

2024-01-23 09:51 UTC, abelkov commented on plugins/kotlin/j2k/k1.new/src/org/jetbrains/kotlin/nj2k/printing/JKCodeBuilder.kt
> +                        (modifiersListOwner is JKMethod && modifiersListOwner.parentOfType<JKClass>()?.classKind == INTERFACE)
It looks like there is too much indentation here, please reformat this line.

2024-01-23 10:02 UTC, abelkov commented
The change itself looks good. All current J2K tests are passing.

2024-01-23 10:20 UTC, darthorimar commented on plugins/kotlin/j2k/k1.new/src/org/jetbrains/kotlin/nj2k/printing/JKCodeBuilder.kt
> +            val isInterface = (modifiersListOwner is JKClass && modifiersListOwner.classKind == INTERFACE) ||
I would rename it to `isOpenByDefault` or smth similar because now it's `true` not only for interfaces.

2024-01-23 14:02 UTC, jocelynluizzi13 commented on .idea/vcs.xml
I'm not sure how the `.idea` files got into this commit to begin with, I tried to revert them but it's still showing a change to the final line.

2024-01-24 09:50 UTC, abelkov approved these changes

2024-01-24 12:08 UTC, closed without merging