[kotlin] K2 J2K: Move VarToValProcessing LocalVarToValInspectionBasedProcessing and fixValToVarDiagnosticBasedProcessing to JKTree
JetBrains/intellij-community pull request #2743
Opened 2024-04-24 18:13 UTC by jocelynluizzi13

(continuation of https://github.com/JetBrains/intellij-community/pull/2702 and https://github.com/JetBrains/intellij-community/pull/2726)

@darthorimar requested that I move the process of determining mutability earlier as it will be faster in the psi/java side of things. However, after completing it in this pull request I feel like this is actually impossible. There are many such cases where the code changes after the `JKBuilder` phase that would change mutability. For example:

- testData/newJ2k/issues/kt-19340.java. `s1` and `s2` are initially stub expressions and are only defined once in the class. This would indicate that they can be `val`. However, by `kt-19340.kt`, `s1` and `s2` are set equal to null initially, and thus have their values changed. There are many more such instances of this.

additionally, per slack discussion we have noted that `nameConflict4` and `nameConflict5` should be in a run block. However, the j2k is not creating these run blocks, hence those tests failing here.

Thanks in advance for any feedback!

@abelkov @darthorimar @ermattt

2024-05-15 04:43 UTC, darthorimar commented
> testData/newJ2k/issues/kt-19340.java. s1 and s2 are initially stub expressions and are only defined once in the class.

This case can be handled separately, eg., you can use `FinalUtils.canBeFinal` instead of `FinalUtils.isImmutableField` which seems to be handling the case.

> additionally, per slack discussion we have noted that nameConflict4 and nameConflict5 should be in a run
Tests seem to be failing because of comparing declarations by name in `PsiLocalVariable.toJK()`. Please create a new function 
 `HashSet<PsiVariable> calculateVariablesWhichCanBeFinalInBlocks(final PsiCodeBlock body)` in `LocalCanBeFinal` extracting the logic from `checkCodeBlockForImmutability`.

2024-05-15 04:47 UTC, darthorimar requested changes

2024-05-15 04:47 UTC, darthorimar commented on plugins/kotlin/j2k/shared/src/org/jetbrains/kotlin/nj2k/JavaToJKTreeBuilder.kt
> +                    codeBlock.hasMatchingNameAssignment(this) -> MUTABLE
This is not future-proof as there maybe declarations with the same name in the block. What's the reason behind this?

2024-05-15 04:47 UTC, darthorimar commented on plugins/kotlin/j2k/shared/src/org/jetbrains/kotlin/nj2k/JavaToJKTreeBuilder.kt
> +            val codeBlock = parentOfType<PsiCodeBlock>()
This way you will calculate mutability of all fields in the block for each field which may result in quadratic complexity. Let's make the mutability computation to be performed only once per each block

2024-05-30 15:02 UTC, jocelynluizzi13 commented
still having an issue with `kt-22848` because it is a special case `val foo = foo = 5` which doesn't seem to be caught appropriately

also  `DetectProperties#testInObject` is adding a `const` somewhere that I cannot figure out why

Otherwise, this seems to be working !

2024-06-03 15:06 UTC, darthorimar requested changes

2024-06-06 15:47 UTC, jocelynluizzi13 commented on plugins/kotlin/j2k/shared/tests/testData/newJ2k/field/initializedBothWithInitializerAndConstructor.kt
> +        private set
In java, this string is private, but the class is public. Since it's a `var` it should have a private setter or it can be changed from anywhere

2024-06-24 12:06 UTC, darthorimar requested changes

2024-06-24 12:06 UTC, darthorimar commented on plugins/kotlin/j2k/shared/src/org/jetbrains/kotlin/nj2k/JavaToJKTreeBuilder.kt
> +                immutableVariables[codeBlock]?.any { it == this } == true -> IMMUTABLE
`immutableVariables[codeBlock]` is a `Set`. `immutableVariables[codeBlock]?.contains(this) == true` should be faster :)

2024-06-24 14:02 UTC, amaembo requested changes
As Java plugin does not depend on Kotlin, I would request to put Java-specific changes in the separate review, document them and cover them by unit-tests in Java plugin where possible. It should not be the case that a specific behavior in Java plugin is covered by a test inside Kotlin plugin only. Thank you for understanding.

2024-06-24 14:02 UTC, amaembo commented on java/java-analysis-impl/src/com/intellij/codeInspection/localCanBeFinal/LocalCanBeFinal.java
> +                if (declaredElement instanceof PsiVariable) result.add((PsiVariable)declaredElement);
Please rollback the stylistical changes like this. The PR is too long already, and these complicate review. Not to mention that such a change is questionable one.

2024-06-24 14:02 UTC, amaembo commented on java/java-analysis-impl/src/com/intellij/codeInspection/localCanBeFinal/LocalCanBeFinal.java
> -      if (!variable.isPhysical()) continue;
Sorry, I have the same question and don't see the answer.

2024-06-24 16:29 UTC, jocelynluizzi13 commented on java/java-analysis-impl/src/com/intellij/codeInspection/localCanBeFinal/LocalCanBeFinal.java
> -      if (!variable.isPhysical()) continue;
The changes in this file are due to the fact that checking for Immutable variables (what I am trying to do) requires some small changes from checking for final variables. All of this code that looks "deleted" right now still exists, it just for some reason was marked as deleted + readded above.

What I actually did was factor out the tree search mechanism into `checkBlockForImmutableAndFinalVariables`, which is called in both `checkCodeBlock` and my new method `getImmutableLocalVariablesInBlock` .  The method `checkCodeBlock` is left exactly as it was beforehand minus the refactor.

2024-06-24 17:08 UTC, jocelynluizzi13 commented on java/java-psi-impl/src/com/intellij/psi/controlFlow/ControlFlowUtil.java
> +              if (!psiManager.areElementsEquivalent(read.variable, psiVariable) || state.getWriteCount() != 0) {
The `continue` should only be applying to the `while` but is actually applying to the `for` loop here. I will try to write a test case to capture this

2024-08-15 17:54 UTC, closed without merging