Add JAR manifest header structure support
JetBrains/intellij-community pull request #2756
Opened 2024-05-12 17:38 UTC by mkem114

2024-05-12 17:39 UTC, mkem114 commented on java/manifest/src/org/jetbrains/lang/manifest/psi/impl/HeaderImpl.java
> +        return null;
Would love to add an icon, but I don't see a way to generate one like the rest

2024-05-29 08:13 UTC, mkem114 commented
@sirgl Can I please get a review?

2024-06-14 10:51 UTC, amaembo commented
It would be great to see any unit-tests testing the new behavior.

2025-01-10 14:34 UTC, amaembo requested changes
It would be great to see any unit-tests testing the new behavior.

2025-06-23 08:04 UTC, amaembo commented
As there's no reaction from the PR author, the PR gets closed. If you'd like to continue working on this, please create a new PR.

2025-06-23 08:04 UTC, closed without merging